# PostgreSQL configuration
default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['CATALOGO_FILMES_DB_USERNAME'] || 'rafael' %>
  password: <%= ENV['CATALOGO_FILMES_DB_PASSWORD'] || 'gamer' %>
  host: <%= ENV['CATALOGO_FILMES_DB_HOST'] || 'localhost' %>
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: catalogo_filmes_development

test:
  <<: *default
  database: catalogo_filmes_test

production:
  <<: *default
  database: <%= ENV['CATALOGO_FILMES_DATABASE_NAME'] %>
  username: <%= ENV['CATALOGO_FILMES_DATABASE_USERNAME'] %>
  password: <%= ENV['CATALOGO_FILMES_DATABASE_PASSWORD'] %>
  host: <%= ENV['CATALOGO_FILMES_DATABASE_HOST'] %>
  port: <%= ENV['CATALOGO_FILMES_DATABASE_PORT'] || 5432 %>
